name: Package Application with Pyinstaller

on: [push]
permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  winbuild: # Windows build
    name: Build package on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Package application
      run: |
        pyinstaller -i icons/icon.ico -F -w --clean --additional-hooks-dir hooks --log-level WARN main.py

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: win
        path: dist/main.exe

  macbuild: # MacOS Build
    name: Build package on MacOS
    runs-on: macos-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
  
    - name: Package application
      run: |
        pyinstaller -i icons/icon.icns -F -w --clean --additional-hooks-dir hooks --log-level WARN main.py
        cd dist
        zip -r9 ACHelper.zip main.app/

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: mac
        path: dist/ACHelper.zip

  upload: # Upload releases
    name: Upload releases
    runs-on: ubuntu-latest
    needs: [winbuild, macbuild]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3

    - name: Remame artifacts
      run: |
        mv win/main.exe ACHelper-win.exe
        mv mac/ACHelper.zip ACHelper-mac.zip

    - name: Create & upload release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: alpha
        prerelease: true
        title: AtCoder Contest Helper
        files: |
          ACHelper-win.exe
          ACHelper-mac.zip
